### ISSUE TITLE
Add "application" to Stripe charge creation

### ISSUE THREAD

**Issue by pippinsplugins** [SellBirdHQ/theme#74] opened 2017-10-10 17:04 UTC
In order for charges to be connected to the main SellBird application in Stripe, we need to add the `application` parameter to the `\Stripe\Charge::create()` call.

This can be done by filtering `edds_create_charge_args`:

```php
$charge = \Stripe\Charge::create( apply_filters( 'edds_create_charge_args', $args, $purchase_data ) );
```

**Comment by DrewAPicture** [comment] 2017-10-12 00:06
This was a duplicate of #75.

**Closed by DrewAPicture** 2017-10-12 00:06 UTC
Labels: EDD, Stripe
